---
name: clangd
description: |
  clangd build last release with rpath.
homepage: https://clangd.llvm.org
licenses:
  - Apache-2.0
languages:
  - C
  - C++
categories:
  - LSP

source:
  # linux_version@21.1.8
  id: pkg:generic/c/clangd@21.1.0
  download:
    - target: linux_x64_gnu
      files:
        clangd.tar.xz: https://github.com/fcying/tools/releases/download/tools/clangd_linux_amd64.txz
      bin: clangd/bin/clangd

    - target: [darwin_x64, darwin_arm64]
      files:
        clangd.zip: https://github.com/clangd/clangd/releases/download/{{version}}/clangd-mac-{{version}}.zip
      bin: clangd_{{version}}/bin/clangd

    - target: win_x64
      files:
        clangd.zip: https://github.com/clangd/clangd/releases/download/{{version}}/clangd-windows-{{version}}.zip
      bin: clangd_{{version}}/bin/clangd.exe

schemas:
  lsp: vscode:https://raw.githubusercontent.com/clangd/vscode-clangd/master/package.json

bin:
  clangd: "{{source.download.bin}}"

neovim:
  lspconfig: clangd
