---
name: clangd
description: |
  clangd build last release with rpath.
homepage: https://clangd.llvm.org
licenses:
  - Apache-2.0
languages:
  - C
  - C++
categories:
  - LSP

source:
  id: pkg:generic/c/clangd@18.1.6
  download:
    - target: linux_x64_gnu
      files:
        clangd.tar.xz: https://github.com/fcying/tools/releases/download/tools/clangd_linux_amd64.txz
      bin: clangd/bin/clangd

    - target: [darwin_x64, darwin_arm64]
      files:
        clangd.zip: https://github.com/clangd/clangd/releases/download/18.1.3/clangd-mac-18.1.3.zip
      bin: clangd_18.1.3/bin/clangd

    - target: win_x64
      files:
        clangd.zip: https://github.com/clangd/clangd/releases/download/18.1.3/clangd-windows-18.1.3.zip
      bin: clangd_18.1.3/bin/clangd.exe

schemas:
  lsp: vscode:https://raw.githubusercontent.com/clangd/vscode-clangd/master/package.json

bin:
  clangd: "{{source.download.bin}}"
